hadoopPath: /opt/hadoop
apps:
  - id: minimac
    permission: user
    filename: minimac/minimac-vcf.yaml
  - id: minimac-admin
    permission: admin
    filename: minimac/minimac-vcf-admin.yaml
  - id: minimac-hrc
    permission: hrc
    filename: minimac/minimac-vcf-hrc.yaml
  - id: minimac-no-limit
    permission: nolimit
    filename: minimac/minimac-vcf-nolimit.yaml
outputPath: output
tempPath: tmp
localWorkspace: cloudgene-workspace
hdfsWorkspace: cloudgene-workspace
name: UM Imputationserver
removeHdfsWorkspace: true

mail:
  smtp: localhost
  port: 25
  user: 
  password: 
  name: noreply@imputationserver.sph.umich.edu