hadoopPath: /opt/hadoop
apps:
  user: /home/lukas/workspace/minimac-cloud/target/minimac-vcf.yaml
  admin: /home/lukas/workspace/minimac-cloud/target/minimac-vcf-admin.yaml
outputPath: output
tempPath: tmp
localWorkspace: cloudgene-workspace
hdfsWorkspace: cloudgene-workspace
name: UM Imputationserver
removeHdfsWorkspace: true

mail:
  smtp: localhost
  port: 25
  user: 
  password: 
  name: noreply@imputationserver.sph.umich.edu
